FROM beveradb/audio-separator:gpu

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

ENTRYPOINT []
WORKDIR /app

COPY pyproject.toml ./
COPY app ./app
RUN --mount=type=cache,target=/root/.cache/pip pip3 install .

CMD ["python3", "-m", "app.worker.main"]
